accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views
import inbox.views
# from inbox.views import create_conversation


app_name = 'accounts'

urlpatterns = [

    path('signup/completion/no-invite', views.post_signup_uninvited, name='post_signup_uninvited'),
    path('signup/completion/invite', views.post_signup_invitee, name='post_signup_invitee'),
    path('signup/completion/organization', views.post_signup_organization, name='post_signup_organization'),
    path('signup/user-type/select', views.select_user_type, name='user_type_select'),
    path('invitations/send', views.invite_user, name='user_invite'),
    path('invitations/<int:pk>/resend', views.resend_invite, name='invite_resend'),
    path('invitations/signup/', views.invitee_signup, name='signup_invitee'),
    path('settings/', views.settings, name='settings'),
    path('settings/banking/update', views.update_bank_account, name='banking_update'),
    path('settings/profile/update', views.update_profile, name='profile_update'),
    path('settings/deactivate/confirm', views.account_confirm_deactivate, name='account_confirm_deactivate'),

    path('<str:username>/update', views.update_user, name='user_update'),
    path('<str:username>/message', inbox.views.create_conversation, name='conversation_create'), ###

    path('landlords', views.list_profiles, name='landlord_list'),
    path('tenants', views.list_profiles, name='tenant_list'),
    path('merchants', views.list_profiles, name='merchant_list'),



    path('buildings/create', views.create_building, name='building_create'),
    path('buildings/<int:pk>/update', views.update_building, name='building_update'),
    path('buildings/<int:pk>/delete', views.delete_building, name='building_delete'),
    path('buildings', views.list_buildings, name='building_list'),

    path('bookings/create', views.create_booking, name='booking_create'),
    path('bookings', views.list_bookings, name='booking_list'),

    path('notifications', views.notifications, name='notifications'),

    
    # path('<int:pk>/create_password/', views.create_password, name='password_create'),
    # path('create/', views.create_user, name='user_create'),
    # path('new_user/',views.new_user_signup,name='new_user_signup'),
    # path('delete/account/', views.delete_account, name='delete_account'),
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('<int:pk>/completion/', views.select_user_type, name='user_type_select'),
    # path("hello/", allauth.account.views.PasswordChangeView, name=""),
]

dashboard/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from dashboard import views
from django.urls import reverse_lazy

app_name = 'dashboard'

urlpatterns = [
    # path('', views.Home.as_view(), name='home'),
    path('', views.home, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    # path('<str:slug>/dashboard', views.dashboard, name='dashboard'),
    path('organization/<str:slug>', views.list_listings, name='listing_list'),
    path('organization/<str:slug>/listing/<str:pk>', views.listing, name='listing'),
    path('organization/<str:slug>/checkout/<str:pk>', views.check_out, name='check_out'),

    
]

jawa/urls.py
from django.contrib import admin
from django.urls import path, include
import allauth

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include("dashboard.urls", namespace="dashboard")),
    path('inbox/', include("inbox.urls", namespace="inbox")),
    path('invitations/', include('invitations.urls', namespace='invitations')),
    # path('hello/', include('allauth.urls')),
]

#     ^$ ^ ^signup/$ [name='account_signup']
#     ^$ ^ ^login/$ [name='account_login']
#     ^$ ^ ^logout/$ [name='account_logout']
#     ^$ ^ ^password/change/$ [name='account_change_password']
#     ^$ ^ ^password/set/$ [name='account_set_password']
#     ^$ ^ ^inactive/$ [name='account_inactive']
#     ^$ ^ ^email/$ [name='account_email']
#     ^$ ^ ^confirm-email/$ [name='account_email_verification_sent']
#     ^$ ^ ^confirm-email/(?P<key>[-:\w]+)/$ [name='account_confirm_email']
#     ^$ ^ ^password/reset/$ [name='account_reset_password']
#     ^$ ^ ^password/reset/done/$ [name='account_reset_password_done']
#     ^$ ^ ^password/reset/key/(?P<uidb36>[0-9A-Za-z]+) -(?P<key>.+)/$ [name='account_reset_password_from_key']
#     ^$ ^ ^password/reset/key/done/$ [name='account_reset_password_from_key_done']
#     ^$ ^social/
#     ^$ ^google/
#     ^$ ^facebook/
#     ^$ ^facebook/login/token/$ [name='facebook_login_by_token']
#     ^admin/

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from invitations.utils import get_invitation_model
from django.core.exceptions import ObjectDoesNotExist
from datetime import date
from datetime import datetime as dt
from jawa.utils import get_time_ago
from django.template.defaultfilters import slugify
from accounts.choices import *
from multiselectfield import MultiSelectField

# from inbox.models import *
# from inbox.models import *



class OrganizationProfile(models.Model):
    name = models.CharField(max_length=45)
    slug = models.SlugField(null=False, unique=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

class User(AbstractUser):
    USER_TYPE_CHOICES  = [
        (0, ''), ## Necessary for social signups
        (1, 'tenant'),
        (2, 'landlord'),
        (3, 'merchant'),
        (4, 'property manager'),
    ]

    PROVINCES_CHOICES= [
        ('AB', 'Alberta'),
        ('BC', 'British Columbia'),
        ('MB', 'Manitoba'),
        ('NB', 'New Brunswick'),
        ('NL', 'Newfoundland and Labrador'),
        ('NT', 'Northwest Territories'),
        ('NS', 'Nova Scotia'),
        ('NU', 'Nunavut'),
        ('ON', 'Ontario'),
        ('NB', 'Prince Edward Island'),
        ('QC', 'Quebec'),
        ('SK', 'Saskatchewan'),
        ('YT', 'Yukon'),
    ]

    COUNTRIES_CHOICES= [
        ('CA','Canada'),
    ]

    ACCOUNT_TYPES = [
        ('CA','Canadian'),
    ]

    YEARS_CHOICES= [
        ('', '--'),
        (abs(date.today().year) % 100, date.today().year),
        (abs(date.today().year+1) % 100, date.today().year +1),
        (abs(date.today().year+2) % 100, date.today().year +2),
        (abs(date.today().year+3) % 100, date.today().year +3),
        (abs(date.today().year+4) % 100, date.today().year +4),
        (abs(date.today().year+5) % 100, date.today().year +5),
        (abs(date.today().year+6) % 100, date.today().year +6),
        (abs(date.today().year+7) % 100, date.today().year +7),
        (abs(date.today().year+8) % 100, date.today().year +8),
        (abs(date.today().year+9) % 100, date.today().year +9),
        (abs(date.today().year+10) % 100, date.today().year +10),
    ]

    MONTHS_CHOICES= [
        ('', '--'),
        ('01', '01'),
        ('02', '02'),
        ('03', '03'),
        ('04', '04'),
        ('05', '05'),
        ('06', '06'),
        ('07', '07'),
        ('08', '08'),
        ('09', '09'),
        ('10', '10'),
        ('11', '11'),
        ('12', '12')
    ]

    user_type = models.PositiveSmallIntegerField(choices=USER_TYPE_CHOICES, default=0)
    organization = models.ForeignKey(OrganizationProfile, related_name='user', null=True, on_delete=models.SET_NULL)
    phone = models.CharField(max_length=18, blank=True)

    bank_account_holder = models.CharField(max_length=50, blank=True)
    bank_account_type = models.CharField(max_length=2, choices=ACCOUNT_TYPES, default='CA', blank=True)
    institution_number = models.CharField(max_length=3, blank=True)
    branch_number = models.CharField(max_length=5, blank=True)
    account_number= models.CharField(max_length=12, blank=True)

    card_name = models.CharField(max_length=50, blank=True)
    card_number = models.CharField(max_length=16, blank=True)
    card_expiry_month = models.CharField(max_length=2, choices=MONTHS_CHOICES, blank=True)
    card_expiry_year = models.CharField(max_length=2, choices=YEARS_CHOICES, blank=True)
    card_cvd = models.CharField(max_length=5, blank=True)

    def get_absolute_url(self):
        return reverse('home')
    
    def __str__(self):
        if self.first_name and self.last_name:
            return "{} {}".format(self.first_name, self.last_name)
        return self.username

class ManagerProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, related_name='manager_profile')

    def __str__(self):
        return str(self.user)

class TenantProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, related_name='tenant_profile')

    def __str__(self):
        return str(self.user)

class LandlordProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, related_name='landlord_profile')

    def __str__(self):
        return str(self.user)

class MerchantProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, related_name='merchant_profile')

    def __str__(self):
        return str(self.user)



class Building(models.Model):

    # def __init__(self, *args, **kwargs):
    #     super(Building, self).__init__(*args, **kwargs)
    #     self.__original_category = self.category

    landlord = models.ForeignKey('LandlordProfile', on_delete=models.CASCADE)
    address = models.CharField(max_length=50)
    unit = models.CharField(max_length=5, blank=True)
    size = models.PositiveSmallIntegerField(choices=UNIT_SIZE_OPTIONS)
    bath = models.PositiveSmallIntegerField()
    rental_type = models.PositiveSmallIntegerField(choices=RENTAL_OPTIONS)
    # rental_type = MultiSelectField(choices=RENTAL_OPTIONS)

    def __str__(self):
        if self.unit:
            return str("{}-{}".format(self.unit, self.address))
        return self.address


@receiver(post_save, sender=Building)
def auto_create_unit_with_building(sender, instance, **kwargs):
    # import pdb; pdb.set_trace()
    ## Building is created V1
    # if kwargs['created']:
    #     if instance.category == 1:
    #         RentalUnit.objects.create(apartment=instance, room_no='')
    #     else:
    #         # import pdb; pdb.set_trace()
    #         units = [RentalUnit(apartment=instance, room_no=j) for j in range(1, instance.size + 1)]
    #         RentalUnit.objects.bulk_create(units)

    if kwargs['created']:
        rooms = [RentalUnit(apartment=instance, room_no=j, unit_type=2) for j in range(1, instance.size + 1)]
        unit = [RentalUnit(apartment=instance, room_no='', unit_type=1)]
        import pdb; pdb.set_trace()
        all_units = rooms + unit
        RentalUnit.objects.bulk_create(all_units)




    ## Building is updated
    # else:
    #     print('update to building')
    #     if instance.category != instance._Building__original_category:
    #         print('specific update to category')
    #         RentalUnit.objects.filter(apartment=instance).delete()
    #         print('deleting all existing listings')
    #         import pdb; pdb.set_trace()
    #         if instance.category == 1:
                
    #             print('creating 1 listing')
    #             RentalUnit.objects.create(apartment=instance, room_no='')
    #         else:
    #             print('creating {} listings'.format(instance.size))
    #             units = [RentalUnit(apartment=instance, room_no=j) for j in range(1, instance.size + 1)]
    #             import pdb; pdb.set_trace()
    #             RentalUnit.objects.bulk_create(units)
    #             instance.size = len(RentalUnit.objects.filter(apartment=instance))
    #             instance.save()








class RentalUnit(models.Model):
    apartment = models.ForeignKey('Building', related_name='rental_unit', on_delete=models.CASCADE)
    unit_type = models.PositiveSmallIntegerField(choices=UNIT_TYPE)
    room_no = models.CharField(max_length=5, blank=True)
    
    def __str__(self):
        if self.unit_type == 2:
        # if self.apartment.category == 2: V1
        # if self.room_no: V0
            return str("{} · Room {}".format(self.apartment, self.room_no))
        return str("{} · Entire unit".format(self.apartment))

# @receiver(post_delete, sender=RentalUnit) ## V1
# def auto_update_unit_size_when_delete(sender, instance, **kwargs):
#     # import pdb; pdb.set_trace()
#     instance.apartment.size = len(RentalUnit.objects.filter(apartment=instance.apartment))
#     # if instance.apartment.size == 1:
#     #     instance.apartment.category = 1
#     instance.apartment.save()

# @receiver(post_save, sender=RentalUnit)
# def auto_update_unit_size_when_create(sender, instance, **kwargs):
#     # import pdb; pdb.set_trace()
#     instance.apartment.size = len(RentalUnit.objects.filter(apartment=instance.apartment))
#     instance.apartment.save()


@receiver(post_delete, sender=RentalUnit)
def auto_update_unit_size_when_delete(sender, instance, **kwargs):
    # import pdb; pdb.set_trace()
    instance.apartment.size = len(RentalUnit.objects.filter(apartment=instance.apartment, unit_type=2))
    instance.apartment.save()

@receiver(post_save, sender=RentalUnit)
def auto_update_unit_size_when_create(sender, instance, **kwargs):
    # import pdb; pdb.set_trace()
    instance.apartment.size = len(RentalUnit.objects.filter(apartment=instance.apartment, unit_type=2))
    instance.apartment.save()

class Booking(models.Model):
    STATUS_OPTIONS = [
        (0, 'Pending'),
        (1, 'Accepted'),
        (2, 'In-tenancy'),
        (3, 'Moved-out'),
        (4, 'Cancelled'),
    ]
    status = models.PositiveSmallIntegerField(choices=STATUS_OPTIONS, default=0)
    tenant = models.ForeignKey('TenantProfile', on_delete=models.CASCADE, related_name='booking')
    building = models.ForeignKey('Building', on_delete=models.CASCADE)
    check_in = models.DateField(blank=False)
    check_out = models.DateField(blank=False)
    rent = models.DecimalField(max_digits=6, decimal_places=2, blank=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


    def __str__(self):
        return str('{} - {} ({})'.format(self.check_in, self.check_out,self.tenant))
    
    def get_model_name(self):
        model_name = 'Booking'

accounts/templates/accounts/bank_account_form.html
{% block body_block %}

<h3><a href="{% url 'dashboard:home' %}">Jawa</a> > <a href="{% url 'dashboard:dashboard' %}">Dashboard</a> > <a href="{% url 'accounts:settings' %}">Settings</a> > <b>Banking Details</b></h3>
<h4>Logged in as {{user}} ({{user.get_user_type_display}})</h4>    

<h1>Update Banking Information</h1>
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>

{% endblock %}

accounts/templates/accounts/booking_form.html
{% block body_block %}

<h3><a href="{% url 'dashboard:home' %}">Jawa</a> > <a href="{% url 'dashboard:dashboard' %}">Dashboard</a> > <b>Create new booking</b></h3>
<h4>Logged in as {{user}} ({{user.get_user_type_display}})</h4>

<h1>Create a booking</h1>
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>

{% endblock %}

accounts/templates/accounts/booking_list.html
{% block body_block %}

<h3><a href="{% url 'dashboard:home' %}">Jawa</a> > <a href="{% url 'dashboard:dashboard' %}">Dashboard</a> > <b>Bookings</b></h3>
<h4>Logged in as {{user}} ({{user.get_user_type_display}})</h4>

<table>
    <tr>
        <th>No</th>
        <th>Status</th>
        <th>Tenant</th>
        <th>Check-in</th>
        <th>Check-out</th>
        <th>Rent</th>
        <th>Action</th>
    </tr>
{% for booking in bookings %}
    <tr>
        <td>{{booking.id}}</td>
        <td>{{booking.get_status_display}}</td>
        <td>{{booking.tenant.user.first_name}} {{booking.tenant.user.last_name}}</td>
        <td>{{booking.check_in}}</td>
        <td>{{booking.check_out}}</td>
        <td>{{booking.rent}}</td>
        <td>
            <a href="">Edit</a>
            <a href="">Delete</a>
        </td>
    </tr>
{% endfor %}
</table>


<style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
        width:auto;
        padding: 5px;
    }
</style>
    


{% endblock %}

accounts/templates/accounts/building_confirm_delete.html
{% block body_block %}
<h1>Delete building</h1>
<p>Are you sure you want to delete {{building}}?</p>
<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Delete">
</form>
<a href="{% url 'accounts:building_list' %}"><button>Nevermind</button></a>

{% endblock %}

accounts/templates/accounts/building_form.html
{% block body_block %}

<h3><a href="{% url 'dashboard:home' %}">Jawa</a> > <a href="{% url 'dashboard:dashboard' %}">Dashboard</a> > <b>Create new building</b></h3>
<h4>Logged in as {{user}} ({{user.get_user_type_display}})</h4>

<h1>Create a building</h1>
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>

{% endblock %}

accounts/templates/accounts/building_list.html
{% block body_block %}

<h3><a href="{% url 'dashboard:home' %}">Jawa</a> > <a href="{% url 'dashboard:dashboard' %}">Dashboard</a> > <b>buildings</b></h3>
<h4>Logged in as {{user}} ({{user.get_user_type_display}})</h4>

<table>
    <tr>
        <th>No</th>
        <th>Unit</th>
        <th>Address</th>
        <th>Landlord</th>
        <th>Action</th>
    </tr>
{% for building in buildings %}
    <tr>
        <td>{{building.id}}</td>
        <td>{{building.unit}}</td>
        <td>{{building.address}}</td>
        <td>{{building.landlord.user.first_name}} {{building.landlord.user.last_name}}</td>
        <td>
            <a href="{% url 'accounts:building_update' pk=building.id%}">Edit</a>
            <a href="{% url 'accounts:building_delete' pk=building.id%}">Delete</a>
        </td>
    </tr>
{% endfor %}
</table>


<style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
        width:auto;
        padding: 5px;
    }
</style>
    


{% endblock %}

accounts/templates/accounts/invite_form.html
{% block body_block %}

<h3><a href="{% url 'dashboard:home' %}">Jawa</a> > <a href="{% url 'dashboard:dashboard' %}">Dashboard</a> > <b>Invite new users</b></h3>
<h4>Logged in as {{user}} ({{user.get_user_type_display}})</h4>

<h1>Send an invitation</h1>
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>

{% endblock %}

accounts/templates/accounts/invite_list.html
{% block body_block %}

<h3><a href="{% url 'dashboard:home' %}">Jawa</a> > <a href="{% url 'dashboard:dashboard' %}">Dashboard</a> > <b>Invite List</b></h3>
<h4>Logged in as {{user}} ({{user.get_user_type_display}})</h4>

<table>
    <tr>
        <th>No</th>
        <th>Email</th>
        <th>Type</th>
        <th>Action</th>
    </tr>
{% for invitation in invitations %}
    <tr>
        <td>{{invitation.id}}</td>
        <td>{{invitation.email}}</td>
        <td>{{invitation.get_user_type_display}}</td>
        <td><a href="{% url 'accounts:invite_resend' pk=invitation.id %}">Resend</a></td>
    </tr>
{% endfor %}
</table>


<style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
        width:20%
    }
</style>
    


{% endblock %}

accounts/templates/accounts/invitee_signup_form.html
{% block content %}

<h1>Sign Up Mogadishu</h1>

<p>Already have an account? Then please <a href="{{ login_url }}">sign in</a></p>

<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>

<script>
    document.getElementById('id_user_type').style.display = "none"
    document.querySelector("label[for='id_user_type']").style.display = "none"
</script>

{% endblock %}

accounts/templates/accounts/post_signup_form.html
{% block body_block %}

<h1>Complete your profile</h1>
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>

{% endblock %}

accounts/templates/accounts/profile_details_form.html
{% block body_block %}

<h3><a href="{% url 'dashboard:home' %}">Jawa</a> > <a href="{% url 'dashboard:dashboard' %}">Dashboard</a> > <a href="{% url 'accounts:settings' %}">Settings</a> > <b>Contact Details</b></h3>
<h4>Logged in as {{user}} ({{user.get_user_type_display}})</h4>    

<h1>Update Contact Details</h1>
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>

{% endblock %}

accounts/templates/accounts/profile_list.html
{% block body_block %}

<h3><a href="{% url 'dashboard:home' %}">Jawa</a> > <a href="{% url 'dashboard:dashboard' %}">Dashboard</a> >
<b>
    {% if user_type == 1 %} Tenants 
    {% elif user_type == 2 %} Landlords
    {% elif user_type == 3 %} Merchants 
    {% endif %}
</b></h3>
<h4>Logged in as {{user}} ({{user.get_user_type_display}})</h4>

<table>
    <tr>
        <th>No</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Email</th>
        <th>Action</th>
    </tr>
{% for user_profile in user_profiles %}
    <tr>
        <td>{{user_profile.id}}</td>
        <td>{{user_profile.user.first_name}}</td>
        <td>{{user_profile.user.last_name}}</td>
        <td>{{user_profile.user.email}}</td>
        <td>
            <a href="{% url 'accounts:user_update' username=user_profile.user.username %}">Edit</a>
            <a href="{% url 'accounts:conversation_create' username=user_profile.user.username %}">Contact</a>
        </td>
    </tr>
{% endfor %}
</table>


<style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
        width:auto;
        padding: 5px;
    }
</style>
    


{% endblock %}

accounts/templates/accounts/select_user_type_form.html
{% block body_block %}

<h1>Select your account type</h1>
<form action="{% url 'accounts:user_type_select' %}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>

{% endblock %}

accounts/templates/accounts/settings.html
{% block body_block %}

<h3><a href="{% url 'dashboard:home' %}">Jawa</a> > <a href="{% url 'dashboard:dashboard' %}">Dashboard</a> > <b>Settings</b></h3>
<h4>Logged in as {{user}} ({{user.get_user_type_display}})</h4>    

<h4>Menu</h4>
<ul>
    <li><a href="{% url 'accounts:profile_update' %}">Profile</a></li>
    <li><a href="{% url 'accounts:banking_update' %}">Banking Details</a></li>
    <li><a href="{% url 'account_change_password' %}">Change Password</a></li>
    <li><a href="{% url 'account_email' %}">Manage Email</a></li>
    <li><a href="{% url 'socialaccount_connections' %}">Social Connections</a></li>
    <li><a href="{% url 'accounts:account_confirm_deactivate' %}">Deactivate Account</a></li>
</ul>

{% endblock %}