accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views
import inbox.views
# from inbox.views import create_conversation


app_name = 'accounts'

urlpatterns = [

    path('signup/completion/no-invite', views.post_signup_uninvited, name='post_signup_uninvited'),
    path('signup/completion/invite', views.post_signup_invitee, name='post_signup_invitee'),
    path('signup/completion/organization', views.post_signup_organization, name='post_signup_organization'),
    path('signup/user-type/select', views.select_user_type, name='user_type_select'),
    path('invitations/send', views.invite_user, name='user_invite'),
    path('invitations/<int:pk>/resend', views.resend_invite, name='invite_resend'),
    path('invitations/signup/', views.invitee_signup, name='signup_invitee'),
    path('settings/', views.settings, name='settings'),
    path('settings/banking/update', views.update_bank_account, name='banking_update'),
    path('settings/profile/update', views.update_profile, name='profile_update'),
    path('settings/deactivate/confirm', views.account_confirm_deactivate, name='account_confirm_deactivate'),

    path('<str:username>/update', views.update_user, name='user_update'),
    path('<str:username>/message', inbox.views.create_conversation, name='conversation_create'), ###

    path('landlords', views.list_profiles, name='landlord_list'),
    path('tenants', views.list_profiles, name='tenant_list'),
    path('merchants', views.list_profiles, name='merchant_list'),



    path('buildings/create', views.create_building, name='building_create'),
    path('buildings/<int:pk>/update', views.update_building, name='building_update'),
    path('buildings/<int:pk>/delete', views.delete_building, name='building_delete'),
    path('buildings', views.list_buildings, name='building_list'),

    path('bookings/create', views.create_booking, name='booking_create'),
    path('bookings', views.list_bookings, name='booking_list'),

    path('notifications', views.notifications, name='notifications'),

    
    # path('<int:pk>/create_password/', views.create_password, name='password_create'),
    # path('create/', views.create_user, name='user_create'),
    # path('new_user/',views.new_user_signup,name='new_user_signup'),
    # path('delete/account/', views.delete_account, name='delete_account'),
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('<int:pk>/completion/', views.select_user_type, name='user_type_select'),
    # path("hello/", allauth.account.views.PasswordChangeView, name=""),
]

dashboard/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from dashboard import views
from django.urls import reverse_lazy

app_name = 'dashboard'

urlpatterns = [
    # path('', views.Home.as_view(), name='home'),
    path('', views.home, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    # path('<str:slug>/dashboard', views.dashboard, name='dashboard'),
    path('organization/<str:slug>', views.list_listings, name='listing_list'),
    path('organization/<str:slug>/listing/<str:pk>', views.listing, name='listing'),
    path('organization/<str:slug>/checkout/<str:pk>', views.check_out, name='check_out'),

    
]

inbox/urls.py
from django.contrib import admin
from django.urls import path, include
from inbox import views

app_name = 'inbox'

urlpatterns = [

    path('', views.list_conversations, name='conversation_list'),
    # path('conversation/<int:pk>', views.list_messages, name='message_list'),
    path('conversation/<int:pk>/messages', views.read_or_send_message, name='message_read_or_send'),
    path('conversation/create', views.create_conversation, name='conversation_create'),

    # path('conversation/create', views.create_conversation2, name='conversation_create2'),
    
]

jawa/urls.py
from django.contrib import admin
from django.urls import path, include
import allauth

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include("dashboard.urls", namespace="dashboard")),
    path('inbox/', include("inbox.urls", namespace="inbox")),
    path('invitations/', include('invitations.urls', namespace='invitations')),
    # path('hello/', include('allauth.urls')),
]

#     ^$ ^ ^signup/$ [name='account_signup']
#     ^$ ^ ^login/$ [name='account_login']
#     ^$ ^ ^logout/$ [name='account_logout']
#     ^$ ^ ^password/change/$ [name='account_change_password']
#     ^$ ^ ^password/set/$ [name='account_set_password']
#     ^$ ^ ^inactive/$ [name='account_inactive']
#     ^$ ^ ^email/$ [name='account_email']
#     ^$ ^ ^confirm-email/$ [name='account_email_verification_sent']
#     ^$ ^ ^confirm-email/(?P<key>[-:\w]+)/$ [name='account_confirm_email']
#     ^$ ^ ^password/reset/$ [name='account_reset_password']
#     ^$ ^ ^password/reset/done/$ [name='account_reset_password_done']
#     ^$ ^ ^password/reset/key/(?P<uidb36>[0-9A-Za-z]+) -(?P<key>.+)/$ [name='account_reset_password_from_key']
#     ^$ ^ ^password/reset/key/done/$ [name='account_reset_password_from_key_done']
#     ^$ ^social/
#     ^$ ^google/
#     ^$ ^facebook/
#     ^$ ^facebook/login/token/$ [name='facebook_login_by_token']
#     ^admin/

inbox/models.py
from django.db import models
from accounts.models import User, Booking
from jawa.utils import get_time_ago
from datetime import date
from datetime import datetime as dt
from django.utils import timezone
from django.db.models.signals import post_save
from django.dispatch import receiver
from inbox.choices import *



# Create your models here.
class Conversation(models.Model):

    category = models.PositiveSmallIntegerField(choices=CONVERSATION_CATEGORY, default=1)
    creator = models.ForeignKey(User, related_name="creator", on_delete=models.CASCADE, null=True)
    recipient = models.ForeignKey(User, related_name="recipient", on_delete=models.CASCADE, null=True)
    updated = models.DateTimeField(auto_now_add=True)
    # is_read = models.BooleanField(default=False)

    # booking = models.OneToOneField(Booking, on_delete=models.CASCADE, null=True, related_name='booking')

    def __str__(self):
        return str(self.id)
    
    @property
    def is_read(self):
        # import pdb; pdb.set_trace()
        all_status_list = MessageStatus.objects.filter(message__in=self.message.all())
        unread_list = all_status_list.filter(is_read=False)
        if unread_list.exists():
            return False
        return True

    
    def get_last_message(self):
        last_message = self.message.all().order_by('-created')[0]
        return last_message
    
    #### To display how long ago the last message was sent
    def get_updated_ago(self):
        delta = dt.now(timezone.utc) - self.updated
        seconds = round(delta.total_seconds())
        updated_ago = get_time_ago(seconds)
        return updated_ago
    

class Message(models.Model):
    conversation = models.ForeignKey(Conversation, related_name="message", on_delete=models.CASCADE)
    sender = models.ForeignKey(User, related_name="sender", on_delete=models.CASCADE)
    receiver = models.ForeignKey(User, related_name="receiver", on_delete=models.CASCADE)
    msg_content = models.TextField(max_length=500, blank=True)
    created = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.msg_content[0:15] + "...")

    #### To display how long ago each message was created
    def get_updated_ago(self):
        delta = dt.now(timezone.utc) - self.created
        seconds = round(delta.total_seconds())
        updated_ago = get_time_ago(seconds)
        return updated_ago

    ### Each time a message is created, the parent conversation's timestamp is updated and pulled up in the feed.

    from django.db import transaction

    @transaction.atomic
    def save(self, *args, **kwargs):
        # import pdb; pdb.set_trace()
        conversation = self.conversation
        conversation.updated = dt.now(timezone.utc)
        conversation.save()
        super(Message, self).save(*args, **kwargs)
    
class MessageStatus(models.Model):
    message = models.OneToOneField(Message, on_delete=models.CASCADE, related_name='message_status')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_read = models.BooleanField(default=False)
    read = models.DateTimeField(null=True)


class ConversationStatus(models.Model):
    conversation = models.ForeignKey(Conversation, on_delete=models.CASCADE, related_name='conversation_status')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_read = models.BooleanField(default=False)
    read = models.DateTimeField(null=True)


@receiver(post_save, sender=Message)
def auto_create_message_status_with_message(sender, instance, **kwargs):
    # import pdb; pdb.set_trace()
    if kwargs['created']:

        ## Create message status
        message_status = MessageStatus.objects.create(
            message=instance,
            user=instance.receiver,
        )
        message_status.save()

        ## Update conversation status
        conversation_status = instance.conversation.conversation_status.all().get(user=instance.receiver) 
        conversation_status.is_read = False
        conversation_status.save()


@receiver(post_save, sender=Conversation)
def auto_create_conversation_status_with_conversation(sender, instance, **kwargs):
    # import pdb; pdb.set_trace()
    if kwargs['created']:
        status_creator = ConversationStatus.objects.create(
            conversation=instance,
            user=instance.creator,
        )
        status_recipient = ConversationStatus.objects.create(
            conversation=instance,
            user=instance.recipient,
        )
        status_creator.save()
        status_recipient.save()

inbox/forms.py
from django import forms
from accounts.models import *
from inbox.models import *
from inbox.choices import *

class MessageForm(forms.Form):
    msg_content = forms.CharField(label="Write a reply", max_length=500, widget=forms.Textarea)

class ConversationForm(forms.Form):
    category = forms.ChoiceField(choices = CONVERSATION_CATEGORY, label='Topic', required=True)
    msg_content = forms.CharField(label="Write a message", max_length=500, widget=forms.Textarea)



# class ConversationForm2(forms.Form):
#     # recipient = forms.CharField(max_length=100)
#     msg_content = forms.CharField(label="Write a message", max_length=500, widget=forms.Textarea)
#     # class Meta():
#     #     model = Conversation
#     #     fields = '__all__'

#     def __init__(self, *args, **kwargs):
#         # import pdb; pdb.set_trace()
#         self.user = kwargs.pop('user',None)
#         super(ConversationForm2, self).__init__(*args, **kwargs)
#         if self.user.user_type == 4:
#             organization = self.user.organization_profile
#             landlords = User.objects.filter(landlord_profile__organization=organization)
#             tenants = User.objects.filter(tenant_profile__organization=organization)
#             merchants = User.objects.filter(merchant_profile__organizations=organization)
#             users = landlords | tenants | merchants  
#             self.fields['recipient'] = forms.ModelChoiceField(queryset=users)
#         # else:

inbox/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import user_passes_test, login_required
from jawa.decorators import post_signup_required, conversation_required
from inbox.models import *
from django.db.models import Q
from inbox.forms import *
from django.db import transaction
from datetime import date
from datetime import datetime as dt
from django.utils import timezone
from itertools import chain

# Create your views here.

@login_required
def list_conversations(request):
    user = request.user
    thread= Conversation.objects.filter(Q(message__receiver=user) | Q(message__sender=user)).distinct().order_by('-updated')
    conversation_list = []

    # import pdb; pdb.set_trace()
    all_con_status_active_user = ConversationStatus.objects.filter(user=request.user).order_by('read')  


    # import pdb; pdb.set_trace()
    for conversation in thread:
        ### Check if any unread message for this conversation & this user
        all_status_list = MessageStatus.objects.filter(message__in=conversation.message.all())
        unread_list = all_status_list.filter(user=request.user, is_read=False)
        ### If no unread messages for this conversation & user, update conversation to read
        if not unread_list.exists():
            obj = conversation.conversation_status.all().get(user=request.user)
            obj.is_read = True
            obj.read=dt.now(timezone.utc)
            obj.save()

    context = {
        'thread' : all_con_status_active_user
    }
    return render(request, 'inbox/conversation_list.html', context)

@login_required
@conversation_required
def read_or_send_message(request,pk):
    # import pdb; pdb.set_trace()
    
    conversation = Conversation.objects.get(id=pk)
    sender = request.user
    receiver = conversation.recipient if conversation.creator == sender else conversation.creator
    message_list = conversation.message.all().order_by('-created')

    all_status_list = MessageStatus.objects.filter(message__in=conversation.message.all()) ## List of all Message Statuses associated to this conversation
    recipient_status_list = all_status_list.filter(user=request.user, is_read=False) ## Filter to current user & that is_read == False
    recipient_status_list.update(is_read=True, read=dt.now(timezone.utc))

    # import pdb; pdb.set_trace()
    conv_status_list = ConversationStatus.objects.filter(conversation=pk) ## List of all Conversation Statuses associated to this conversation
    user_conv_status_list = conv_status_list.filter(user=request.user, is_read=False)
    user_conv_status_list.update(is_read=True, read=dt.now(timezone.utc))

    if request.method == "POST":
        form = MessageForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            message = Message.objects.create(
                conversation=conversation,
                sender=sender,
                receiver=receiver,
                msg_content=data['msg_content'],
            )
            message.save()

            return redirect('inbox:message_read_or_send', pk=pk )
    else:
        form = MessageForm()
    # import pdb; pdb.set_trace()
    context = {
        'form': form,
        'message_list' : message_list,
        'conversation': conversation
    }
    return render(request, 'inbox/message_form.html', context)

@login_required
@transaction.atomic
def create_conversation(request, username):
    sender = request.user
    # import pdb; pdb.set_trace()
    recipient = User.objects.get(username=username)

    if request.method == "POST":
        form = ConversationForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data

            conversation = Conversation.objects.create(
                creator=sender,
                recipient=recipient,
                category=data['category']
            )
            conversation.save()
            message = Message.objects.create(
                conversation=conversation,
                sender=sender,
                receiver=recipient,
                msg_content=data['msg_content'],
            )
            message.save()

            return redirect('inbox:message_read_or_send', pk=conversation.id)
    else:
        form = ConversationForm()

    context = {
        'form': form,
        'recipient' : recipient
    }

    return render(request, 'inbox/conversation_form.html', context)







# @transaction.atomic
# def create_conversation2(request):
#     user = request.user

#     # import pdb; pdb.set_trace()

#     if request.method == "POST":
#         form = ConversationForm2(data=request.POST, user=user)
#         if form.is_valid():
#             data = form.cleaned_data

#             conversation = Conversation.objects.create(
#                 creator=user,
#                 recipient=data['recipient'],
#             )
#             conversation.save()
#             # import pdb; pdb.set_trace()
#             message = Message.objects.create(
#                 conversation=conversation,
#                 sender=user,
#                 receiver=recipient,
#                 msg_content=data['msg_content'],
#             )
#             message.save()

#             return redirect('inbox:message_read_or_send', pk=conversation.id)
#     else:
#         form = ConversationForm2(user=user)

#     return render(request, 'inbox/conversation_form.html', {'form':form})

inbox/templates/inbox/conversation_form.html
{% block body_block %}

<h3><a href="{% url 'dashboard:home' %}">Jawa</a> > <a href="{% url 'dashboard:dashboard' %}">Dashboard</a> > 
        {% if recipient.user_type == 1 %} <a href="{% url 'accounts:tenant_list' %}">Tenants </a>
        {% elif recipient.user_type == 2 %} <a href="{% url 'accounts:landlord_list' %}">Landlords</a>
        {% elif recipient.user_type == 3 %} <a href="{% url 'accounts:merchant_list' %}">Merchants</a> 
        {% endif %}
    </a> > <b>Conversation with {{recipient}}</b></h3>

<h4>Logged in as {{user}} ({{user.get_user_type_display}})</h4>

<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Send message">
</form>

{% endblock %}

inbox/templates/inbox/conversation_list.html
{% block body_block %}

<h3><a href="{% url 'dashboard:home' %}">Jawa</a> > <a href="{% url 'dashboard:dashboard' %}">Dashboard</a> > <b>Inbox</b></h3>
<h4>Logged in as {{user}} ({{user.get_user_type_display}})</h4>

<table>

{% for status in thread %}

    <tr {% if not status.is_read %} class="unread" {% endif %}>
        <td>
            {% if user == status.conversation.get_last_message.receiver %} {{status.conversation.get_last_message.sender}} {% else %} {{status.conversation.get_last_message.receiver}} {% endif %}
            <br>
            {{status.conversation.get_updated_ago.value}} {{status.conversation.get_updated_ago.units}} ago
        </td>
        <td class='preview'>
            <a href="{% url 'inbox:message_read_or_send' pk=status.conversation.id %}">{{status.conversation.get_last_message}}</a>
            <br>
            {{status.conversation.get_category_display}}
        </td>
        <!-- <td>{% if not conversation.is_read %}Unread{% else %}Read{% endif %}</td> -->
        <td>{% if not status.is_read %} Unread {% else %} Read {% endif %}</td>
    </tr>
</strong>
{% endfor %}
</table>


<style>
    table, th, td {
        border-bottom: 1px solid #c3c3c3;
        border-collapse: collapse;
        width:auto;
        padding: 5px 50px 5px 5px;
    }
    .preview {
        width: 175px;
    }

    .unread{
        font-weight: 700;
        background-color: #rgb(232,232,232)
    }
</style>
    


{% endblock %}

inbox/templates/inbox/message_form.html
{% block body_block %}

<h3><a href="{% url 'dashboard:home' %}">Jawa</a> > <a href="{% url 'dashboard:dashboard' %}">Dashboard</a> > <a href="{% url 'inbox:conversation_list' %}">Inbox</a> > 
    <b>Conversation with 
        {% if user == conversation.creator %} 
                {% if conversation.recipient.user_type == 4 %}
                        {{conversation.recipient.organization}}
                {% else %} 
                        {{conversation.recipient}}
                {% endif %}
        {% else %}
                {% if conversation.creator.user_type == 4 %}
                        {{conversation.creator.organization}}
                {% else %} 
                        {{conversation.creator}}
                {% endif %}
        {% endif %}
    </b></h3>
<h4>Logged in as {{user}} ({{user.get_user_type_display}})</h4>

<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Send reply">
</form>
{% for message in message_list %}
    {% if user.id == message.sender.id %}
    <div class="container">
        <table>
                <tr>
                    <td class="sender">{{message.sender}}<br>
                        {{message.get_updated_ago.value}} {{message.get_updated_ago.units}} ago <br>
                    </td>
                </tr>
                <tr>
                    <td class="message right">{{message.msg_content}}</td>                    
                </tr>
                <tr>
                    <td><div class="read">{% if message.message_status.is_read %} <span class="check">✓</span> READ {% else %} UNREAD {% endif %}</div></td>
                </tr>
        </table>
    {% else %}
        <table class='right'>
                <tr >
                    <td class="receiver">{{message.sender}}<br>
                        {{message.get_updated_ago.value}} {{message.get_updated_ago.units}} ago <br>
                    </td>
                </tr>
                <tr>
                    <td class="message">{{message.msg_content}}</td>
                </tr>
        </table>
    </div>
    {% endif %}
{% endfor %}




<style>

    table { 
        border-collapse: collapse;
        margin-bottom: 20px;
        margin: 0px 50px 20px 50px;
        /* border: solid black 1px; */
    }

    th, td { 
        width:300px; 
        padding:5px 
    } 

    .message{
        background: #e8e8e8;
        
        text-align:left;
        padding: 15px;
    }

    .sender{
        text-align:left; 
    }

    .receiver{
        text-align:right; 
    }
    .read{
        color:rgb(173, 173, 173)  ;
        font-size: x-small
    }
    .check{
        color:rgb(113, 191, 255);
        font-weight: bold;
    }


</style>
    


{% endblock %}